-- Auto-sources the weekly devotional's content so an admin never has to
-- write anything to use the feature: a built-in 24-week starter library
-- (public-domain World English Bible text, "Yahweh" rendered as "the
-- LORD" for familiarity, with an original short reflection per verse).
--
-- seed_default_devotionals() is callable by any authenticated user, but
-- only actually seeds the org they're an admin of, and only if that org
-- has no devotionals yet — safe to call from app code (the onboarding
-- flow, src/app/onboarding/actions.ts, calls it right after
-- create_organization() so every new org gets this for free) or to
-- re-trigger by hand for an org that predates this migration.
create or replace function public.seed_default_devotionals(p_org_id uuid)
returns void
language plpgsql security definer
set search_path = public
as $seed$
begin
  if not exists (
    select 1 from profiles
    where id = auth.uid() and org_id = p_org_id and role = 'admin'
  ) then
    raise exception 'Not authorized to seed devotionals for this organization';
  end if;

  if exists (select 1 from devotionals where org_id = p_org_id) then
    return;
  end if;

  insert into devotionals (org_id, title, scripture_reference, scripture_text, reflection, sort_order)
  values
    (p_org_id, 'God''s Great Love', 'John 3:16', 'For God so loved the world, that he gave his one and only Son, that whoever believes in him should not perish, but have eternal life.', 'This is the whole gospel in one sentence: God didn''t wait for us to get it right before loving us — He gave first. Whatever this week holds, you''re not earning God''s love by how well you serve; you already have it, freely, and everything you do can flow from that instead of toward it.', 1),
    (p_org_id, 'Peace That Guards Your Heart', 'Philippians 4:6-7', 'In nothing be anxious, but in everything, by prayer and petition with thanksgiving, let your requests be made known to God. And the peace of God, which surpasses all understanding, will guard your hearts and your thoughts in Christ Jesus.', 'Paul doesn''t say don''t have anything to worry about — he says bring it to God instead of carrying it alone. Whatever''s weighing on you this week, name it in prayer, add thanksgiving even before it''s resolved, and let His peace stand guard over your heart rather than your worry.', 2),
    (p_org_id, 'The Shepherd Who Restores', 'Psalm 23:1-3', 'The LORD is my shepherd: I shall lack nothing. He makes me lie down in green pastures. He leads me beside still waters. He restores my soul. He guides me in the paths of righteousness for his name''s sake.', 'Even a shepherd''s job is to make the sheep rest, not just find them food. If you''re running on empty from serving, this is permission to let God restore you before your next act of service — a soul that''s been restored serves from fullness, not exhaustion.', 3),
    (p_org_id, 'Strong and Courageous', 'Joshua 1:9', 'Haven''t I commanded you? Be strong and courageous. Don''t be afraid. Don''t be dismayed, for the LORD your God is with you wherever you go.', 'Joshua received this right before stepping into a role far bigger than he felt ready for. Courage here isn''t the absence of fear — it''s moving forward anyway because of who''s going with you. Whatever new thing you''re facing this week, you''re not stepping into it alone.', 4),
    (p_org_id, 'Held By His Hand', 'Isaiah 41:10', 'Don''t you be afraid, for I am with you. Don''t be dismayed, for I am your God. I will strengthen you. Yes, I will help you. Yes, I will uphold you with the right hand of my righteousness.', 'Notice the string of promises: with you, strengthened, helped, upheld. God doesn''t just tell us not to fear — He gives reasons why. When anxiety creeps in this week, hold onto this verse the way you''d hold a hand that''s already holding yours.', 5),
    (p_org_id, 'All Things Working Together', 'Romans 8:28', 'We know that all things work together for good for those who love God, to those who are called according to his purpose.', 'This verse doesn''t promise every individual thing will feel good — it promises God is weaving all of it, even the hard parts, toward good for those who love Him. You may not see the whole tapestry yet; trust the Weaver.', 6),
    (p_org_id, 'Trust Over Understanding', 'Proverbs 3:5-6', 'Trust in the LORD with all your heart, and don''t lean on your own understanding. In all your ways acknowledge him, and he will make your paths straight.', 'Trusting God doesn''t mean you stop thinking — it means you stop needing to have it all figured out before you''ll follow Him. Bring Him into the decision you''re wrestling with this week instead of trying to solve it entirely on your own.', 7),
    (p_org_id, 'Plans to Give You Hope', 'Jeremiah 29:11', 'For I know the thoughts that I think toward you, says the LORD, thoughts of peace, and not of evil, to give you hope and a future.', 'This promise was written to people in exile, waiting years for restoration. It''s not a guarantee of an easy week — it''s a guarantee that God''s intentions toward you are for your good and your hope, even in a season of waiting.', 8),
    (p_org_id, 'Rest for the Weary', 'Matthew 11:28-30', 'Come to me, all you who labor and are heavily burdened, and I will give you rest. Take my yoke upon you, and learn from me, for I am gentle and humble in heart; and you will find rest for your souls. For my yoke is easy, and my burden is light.', 'Jesus doesn''t say stop working — He says work yoked to Him instead of alone. If you''re carrying something heavy into this week, bring it to Him first; His invitation is rest, not more to prove.', 9),
    (p_org_id, 'A New Creation', '2 Corinthians 5:17', 'Therefore if anyone is in Christ, he is a new creation. The old things have passed away. Behold, all things have become new.', 'Whatever labeled you before — a mistake, a habit, a season you''re not proud of — it doesn''t get the final word anymore. In Christ, you get to walk into this week as someone genuinely new, not just forgiven but remade.', 10),
    (p_org_id, 'A Very Present Help', 'Psalm 46:1', 'God is our refuge and strength, a very present help in trouble.', 'Not a distant help — a present one, already here and already available before you even finish asking. Whatever trouble this week brings, you don''t have to wait for God to show up; He already has.', 11),
    (p_org_id, 'Strength Through Christ', 'Philippians 4:13', 'I can do all things through Christ, who strengthens me.', 'Paul wrote this from a jail cell, talking about contentment in both plenty and need — not about winning. The strength isn''t for chasing every ambition; it''s for facing whatever this week actually holds, in Him.', 12),
    (p_org_id, 'Renewed Strength', 'Isaiah 40:31', 'But those who wait for the LORD will renew their strength. They will mount up with wings like eagles. They will run, and not be weary. They will walk, and not faint.', 'Waiting isn''t wasted time in God''s economy — it''s where strength gets renewed. If you feel worn down from serving, this is an invitation to wait on Him before you push harder on your own.', 13),
    (p_org_id, 'Casting Your Cares', '1 Peter 5:7', 'casting all your worries on him, because he cares for you.', 'Notice the reason given isn''t because worrying is pointless — it''s because He cares for you. You''re not handing your worries to an indifferent God; you''re handing them to One who actually wants to carry them.', 14),
    (p_org_id, 'A Renewed Mind', 'Romans 12:2', 'Don''t be conformed to this world, but be transformed by the renewing of your mind, so that you may prove what is the good, well-pleasing, and perfect will of God.', 'Transformation starts in the mind, not just behavior. As you go through this week, pay attention to what''s shaping your thinking, and let God''s word be part of what renews it, not just what corrects you afterward.', 15),
    (p_org_id, 'The Fruit of the Spirit', 'Galatians 5:22-23', 'But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faith, gentleness, and self-control. Against such things there is no law.', 'Fruit grows; it isn''t manufactured by effort alone. If patience or gentleness feels in short supply this week, ask the Spirit to grow it rather than just gritting your teeth to produce it.', 16),
    (p_org_id, 'Where Help Comes From', 'Psalm 121:1-2', 'I will lift up my eyes to the hills. Where does my help come from? My help comes from the LORD, who made heaven and earth.', 'The psalmist asks the question out loud before answering it — it''s worth doing the same. When you feel stuck this week, name where you''re tempted to look for help, then deliberately lift your eyes to the One who made everything you''re looking at.', 17),
    (p_org_id, 'The Substance of Faith', 'Hebrews 11:1', 'Now faith is assurance of things hoped for, proof of things not seen.', 'Faith isn''t pretending the unseen doesn''t matter — it''s confidence that what God has promised is as real as what you can touch. Let that shape how you pray this week, even for things you can''t yet see answered.', 18),
    (p_org_id, 'Joy in Testing', 'James 1:2-4', 'Count it all joy, my brothers, when you fall into various temptations, knowing that the testing of your faith produces endurance. Let endurance have its perfect work, that you may be perfect and complete, lacking in nothing.', 'This is one of the harder commands in Scripture — joy isn''t the trial itself, it''s what the trial is producing in you. If this week is testing your patience, ask what endurance it might be building rather than just wishing it away.', 19),
    (p_org_id, 'He Will Not Forsake You', 'Deuteronomy 31:6', 'Be strong and courageous. Don''t be afraid or scared of them; for the LORD your God himself is who goes with you. He will not fail you nor forsake you.', 'Moses said this to a whole nation about to face giants in a land they''d never lived in. The command to be courageous is always paired with a promise of presence — you''re never asked to be strong on your own strength.', 20),
    (p_org_id, 'Seek First', 'Matthew 6:33', 'But seek first God''s Kingdom, and his righteousness; and all these things will be given to you as well.', 'This comes right after Jesus talks about worrying over food and clothing — practical, everyday concerns. Seeking God first isn''t about ignoring what you need this week; it''s about trusting Him with the ordering of your priorities.', 21),
    (p_org_id, 'What Love Looks Like', '1 Corinthians 13:4-7', 'Love is patient and is kind; love doesn''t envy. Love doesn''t brag, is not proud, doesn''t behave itself inappropriately, doesn''t seek its own way, is not provoked, takes no account of evil; doesn''t rejoice in unrighteousness, but rejoices with the truth; bears all things, believes all things, hopes all things, endures all things.', 'Read this list slowly and replace the word love with your own name — it''s a hard but honest way to see where you''re growing and where you''re not. Let it shape one specific interaction this week, not just your general good intentions.', 22),
    (p_org_id, 'Near to the Brokenhearted', 'Psalm 34:18', 'The LORD is near to those who have a broken heart, and saves those who have a crushed spirit.', 'God isn''t distant from your hardest moments — He''s described as near specifically in brokenness. If your heart is heavy this week, that nearness is a promise, not something you have to perform your way back into.', 23),
    (p_org_id, 'New Every Morning', 'Lamentations 3:22-23', 'It is because of the LORD''s loving kindnesses that we are not consumed, because his compassion doesn''t fail. They are new every morning. Great is your faithfulness.', 'This was written in the middle of genuine grief, not in spite of it — hope right alongside honest sorrow. Whatever didn''t go right last week, God''s mercy toward you isn''t carried over depleted; it''s new again this morning.', 24);
end;
$seed$;

grant execute on function public.seed_default_devotionals(uuid) to authenticated;

-- Backfill: every org that predates this migration and doesn't already
-- have any devotionals gets the starter library immediately, run as the
-- migration itself (bypassing the per-caller admin check above, since
-- there's no single "calling admin" for a bulk backfill).
do $backfill$
declare
  r record;
begin
  for r in select id from organizations o where not exists (select 1 from devotionals d where d.org_id = o.id)
  loop
    insert into devotionals (org_id, title, scripture_reference, scripture_text, reflection, sort_order)
    select r.id, x.title, x.scripture_reference, x.scripture_text, x.reflection, x.sort_order
    from (
      select
        row_number() over () as sort_order,
        title, scripture_reference, scripture_text, reflection
      from (values
        ('God''s Great Love', 'John 3:16', 'For God so loved the world, that he gave his one and only Son, that whoever believes in him should not perish, but have eternal life.', 'This is the whole gospel in one sentence: God didn''t wait for us to get it right before loving us — He gave first. Whatever this week holds, you''re not earning God''s love by how well you serve; you already have it, freely, and everything you do can flow from that instead of toward it.'),
        ('Peace That Guards Your Heart', 'Philippians 4:6-7', 'In nothing be anxious, but in everything, by prayer and petition with thanksgiving, let your requests be made known to God. And the peace of God, which surpasses all understanding, will guard your hearts and your thoughts in Christ Jesus.', 'Paul doesn''t say don''t have anything to worry about — he says bring it to God instead of carrying it alone. Whatever''s weighing on you this week, name it in prayer, add thanksgiving even before it''s resolved, and let His peace stand guard over your heart rather than your worry.'),
        ('The Shepherd Who Restores', 'Psalm 23:1-3', 'The LORD is my shepherd: I shall lack nothing. He makes me lie down in green pastures. He leads me beside still waters. He restores my soul. He guides me in the paths of righteousness for his name''s sake.', 'Even a shepherd''s job is to make the sheep rest, not just find them food. If you''re running on empty from serving, this is permission to let God restore you before your next act of service — a soul that''s been restored serves from fullness, not exhaustion.'),
        ('Strong and Courageous', 'Joshua 1:9', 'Haven''t I commanded you? Be strong and courageous. Don''t be afraid. Don''t be dismayed, for the LORD your God is with you wherever you go.', 'Joshua received this right before stepping into a role far bigger than he felt ready for. Courage here isn''t the absence of fear — it''s moving forward anyway because of who''s going with you. Whatever new thing you''re facing this week, you''re not stepping into it alone.'),
        ('Held By His Hand', 'Isaiah 41:10', 'Don''t you be afraid, for I am with you. Don''t be dismayed, for I am your God. I will strengthen you. Yes, I will help you. Yes, I will uphold you with the right hand of my righteousness.', 'Notice the string of promises: with you, strengthened, helped, upheld. God doesn''t just tell us not to fear — He gives reasons why. When anxiety creeps in this week, hold onto this verse the way you''d hold a hand that''s already holding yours.'),
        ('All Things Working Together', 'Romans 8:28', 'We know that all things work together for good for those who love God, to those who are called according to his purpose.', 'This verse doesn''t promise every individual thing will feel good — it promises God is weaving all of it, even the hard parts, toward good for those who love Him. You may not see the whole tapestry yet; trust the Weaver.'),
        ('Trust Over Understanding', 'Proverbs 3:5-6', 'Trust in the LORD with all your heart, and don''t lean on your own understanding. In all your ways acknowledge him, and he will make your paths straight.', 'Trusting God doesn''t mean you stop thinking — it means you stop needing to have it all figured out before you''ll follow Him. Bring Him into the decision you''re wrestling with this week instead of trying to solve it entirely on your own.'),
        ('Plans to Give You Hope', 'Jeremiah 29:11', 'For I know the thoughts that I think toward you, says the LORD, thoughts of peace, and not of evil, to give you hope and a future.', 'This promise was written to people in exile, waiting years for restoration. It''s not a guarantee of an easy week — it''s a guarantee that God''s intentions toward you are for your good and your hope, even in a season of waiting.'),
        ('Rest for the Weary', 'Matthew 11:28-30', 'Come to me, all you who labor and are heavily burdened, and I will give you rest. Take my yoke upon you, and learn from me, for I am gentle and humble in heart; and you will find rest for your souls. For my yoke is easy, and my burden is light.', 'Jesus doesn''t say stop working — He says work yoked to Him instead of alone. If you''re carrying something heavy into this week, bring it to Him first; His invitation is rest, not more to prove.'),
        ('A New Creation', '2 Corinthians 5:17', 'Therefore if anyone is in Christ, he is a new creation. The old things have passed away. Behold, all things have become new.', 'Whatever labeled you before — a mistake, a habit, a season you''re not proud of — it doesn''t get the final word anymore. In Christ, you get to walk into this week as someone genuinely new, not just forgiven but remade.'),
        ('A Very Present Help', 'Psalm 46:1', 'God is our refuge and strength, a very present help in trouble.', 'Not a distant help — a present one, already here and already available before you even finish asking. Whatever trouble this week brings, you don''t have to wait for God to show up; He already has.'),
        ('Strength Through Christ', 'Philippians 4:13', 'I can do all things through Christ, who strengthens me.', 'Paul wrote this from a jail cell, talking about contentment in both plenty and need — not about winning. The strength isn''t for chasing every ambition; it''s for facing whatever this week actually holds, in Him.'),
        ('Renewed Strength', 'Isaiah 40:31', 'But those who wait for the LORD will renew their strength. They will mount up with wings like eagles. They will run, and not be weary. They will walk, and not faint.', 'Waiting isn''t wasted time in God''s economy — it''s where strength gets renewed. If you feel worn down from serving, this is an invitation to wait on Him before you push harder on your own.'),
        ('Casting Your Cares', '1 Peter 5:7', 'casting all your worries on him, because he cares for you.', 'Notice the reason given isn''t because worrying is pointless — it''s because He cares for you. You''re not handing your worries to an indifferent God; you''re handing them to One who actually wants to carry them.'),
        ('A Renewed Mind', 'Romans 12:2', 'Don''t be conformed to this world, but be transformed by the renewing of your mind, so that you may prove what is the good, well-pleasing, and perfect will of God.', 'Transformation starts in the mind, not just behavior. As you go through this week, pay attention to what''s shaping your thinking, and let God''s word be part of what renews it, not just what corrects you afterward.'),
        ('The Fruit of the Spirit', 'Galatians 5:22-23', 'But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faith, gentleness, and self-control. Against such things there is no law.', 'Fruit grows; it isn''t manufactured by effort alone. If patience or gentleness feels in short supply this week, ask the Spirit to grow it rather than just gritting your teeth to produce it.'),
        ('Where Help Comes From', 'Psalm 121:1-2', 'I will lift up my eyes to the hills. Where does my help come from? My help comes from the LORD, who made heaven and earth.', 'The psalmist asks the question out loud before answering it — it''s worth doing the same. When you feel stuck this week, name where you''re tempted to look for help, then deliberately lift your eyes to the One who made everything you''re looking at.'),
        ('The Substance of Faith', 'Hebrews 11:1', 'Now faith is assurance of things hoped for, proof of things not seen.', 'Faith isn''t pretending the unseen doesn''t matter — it''s confidence that what God has promised is as real as what you can touch. Let that shape how you pray this week, even for things you can''t yet see answered.'),
        ('Joy in Testing', 'James 1:2-4', 'Count it all joy, my brothers, when you fall into various temptations, knowing that the testing of your faith produces endurance. Let endurance have its perfect work, that you may be perfect and complete, lacking in nothing.', 'This is one of the harder commands in Scripture — joy isn''t the trial itself, it''s what the trial is producing in you. If this week is testing your patience, ask what endurance it might be building rather than just wishing it away.'),
        ('He Will Not Forsake You', 'Deuteronomy 31:6', 'Be strong and courageous. Don''t be afraid or scared of them; for the LORD your God himself is who goes with you. He will not fail you nor forsake you.', 'Moses said this to a whole nation about to face giants in a land they''d never lived in. The command to be courageous is always paired with a promise of presence — you''re never asked to be strong on your own strength.'),
        ('Seek First', 'Matthew 6:33', 'But seek first God''s Kingdom, and his righteousness; and all these things will be given to you as well.', 'This comes right after Jesus talks about worrying over food and clothing — practical, everyday concerns. Seeking God first isn''t about ignoring what you need this week; it''s about trusting Him with the ordering of your priorities.'),
        ('What Love Looks Like', '1 Corinthians 13:4-7', 'Love is patient and is kind; love doesn''t envy. Love doesn''t brag, is not proud, doesn''t behave itself inappropriately, doesn''t seek its own way, is not provoked, takes no account of evil; doesn''t rejoice in unrighteousness, but rejoices with the truth; bears all things, believes all things, hopes all things, endures all things.', 'Read this list slowly and replace the word love with your own name — it''s a hard but honest way to see where you''re growing and where you''re not. Let it shape one specific interaction this week, not just your general good intentions.'),
        ('Near to the Brokenhearted', 'Psalm 34:18', 'The LORD is near to those who have a broken heart, and saves those who have a crushed spirit.', 'God isn''t distant from your hardest moments — He''s described as near specifically in brokenness. If your heart is heavy this week, that nearness is a promise, not something you have to perform your way back into.'),
        ('New Every Morning', 'Lamentations 3:22-23', 'It is because of the LORD''s loving kindnesses that we are not consumed, because his compassion doesn''t fail. They are new every morning. Great is your faithfulness.')
      ) as v(title, scripture_reference, scripture_text, reflection)
    ) as x;
  end loop;
end;
$backfill$;
