-- Restructures the devotional into the format Our Daily Bread (odb.org)
-- uses: title, key verse, a short reflection that opens with a relatable
-- story before turning to the passage and its application, then a
-- "Reflect & Pray" close with a question and a short prayer. No ODB text
-- is reused here — this only borrows the structure; all reflections,
-- stories, questions, and prayers are original.

alter table devotionals add column prayer text;
alter table devotionals add column reflection_question text;

-- Rewrites the existing 24-entry library (both current orgs) in place,
-- matched by scripture_reference so it applies regardless of each org's
-- own row ids or sort order.
update devotionals d
set
  title = v.title,
  reflection = v.reflection,
  reflection_question = v.reflection_question,
  prayer = v.prayer
from (
  values
    ('John 3:16', 'God''s Great Love', 'Most of us know at least one parent who''d give up their last dollar, their last hour of sleep, or their own comfort for their child without a second thought — and we call that ordinary love. John describes something far larger: the Creator of the universe giving up His only Son, not for people who''d earned it, but for a world that had turned away from Him.

That''s the whole gospel compressed into one verse — God moved first, before we asked, before we deserved it, before we even knew we needed it. Belief isn''t the price we pay for that love; it''s simply how we receive what''s already been given.

Whatever this week holds, you don''t have to perform your way into God''s affection. You can serve, work, and love other people from a place of already being loved, instead of trying to earn a love you already have.', 'Where this week have you been trying to earn love that God has already freely given you?', 'Father, thank You for loving me before I ever turned toward You. Help me receive Your love today instead of working for it, and let it overflow into how I treat the people around me. Amen.'),
    ('Philippians 4:6-7', 'Peace That Guards Your Heart', 'Anxiety has a way of running the same loop over and over without ever actually solving anything — you can replay a hard conversation fifty times and still feel just as unsettled by evening. Paul, writing this letter from prison, knew that loop well, yet he tells a whole church not to be anxious about anything.

His instruction isn''t to suppress the worry but to redirect it — to turn it into a specific prayer, made with thanksgiving even before the outcome is known. What follows isn''t a guaranteed fix to the circumstance, but something better: a peace that doesn''t depend on the circumstance being fixed at all.

Name the thing that''s looping in your mind this week. Bring it to God in a specific prayer today, and ask Him to stand guard over your heart while you wait.', 'What specific worry could you turn into a specific prayer today, instead of just carrying it silently?', 'Lord, I bring You what''s been circling in my mind. Thank You in advance for how You''ll care for it, and guard my heart with a peace I can''t manufacture on my own. Amen.'),
    ('Psalm 23:1-3', 'The Shepherd Who Restores', 'It''s easy to mistake constant activity for faithfulness — to keep saying yes to one more task, one more shift, one more need, until you''re running on fumes and calling it devotion. David, a shepherd himself before he was a king, knew that even sheep have to be made to lie down; left to themselves, they''ll graze anxiously until they collapse.

That''s exactly the image he uses for God''s care: a shepherd who doesn''t just point out the pasture but leads His people into rest, and doesn''t just feed the body but restores the soul. Rest here isn''t a reward for finishing the work — it''s part of how the Shepherd cares for those who serve.

If you''re running low this week, this isn''t permission to quit serving — it''s an invitation to let God restore you before you serve again.', 'What would it look like this week to let God restore you before your next act of service, instead of after you''ve run out?', 'Shepherd God, restore what serving has emptied out of me. Lead me somewhere quiet before You send me out again, and remind me that resting in You is not wasted time. Amen.'),
    ('Joshua 1:9', 'Strong and Courageous', 'Nobody feels fully ready for the role that finally arrives — the promotion, the new city, the responsibility that''s suddenly yours. Joshua had spent decades as Moses'' assistant, and now he was being handed an entire nation and a land full of giants, with the man who''d led everything before him gone.

God''s command to Joshua isn''t a pep talk about self-confidence — it''s grounded entirely in a promise of presence: "the LORD your God is with you wherever you go." Courage, in Scripture, is rarely the absence of fear; it''s obedience that moves forward anyway because of who''s walking alongside you.

Whatever new responsibility or unfamiliar ground you''re stepping into this week, you''re not being sent out to prove yourself alone.', 'What''s the "giant" in front of you this week that feels too big to face on your own strength?', 'Lord, I don''t feel ready for what''s ahead, but You never asked me to be strong by myself. Go with me into this week, and let Your presence be enough for my courage. Amen.'),
    ('Isaiah 41:10', 'Held By His Hand', 'There''s a particular kind of grip a small child uses crossing a crowded parking lot — not casual, but urgent, both hands, holding on as if letting go for even a second would be dangerous. Isaiah''s audience needed that same kind of grip; they were a people facing exile, invasion, and real reason to be afraid.

God doesn''t respond with a vague reassurance — He stacks four specific promises in one breath: I am with you, I am your God, I will strengthen you, I will uphold you. This isn''t distant comfort; it''s a hand that''s already closed around theirs before they even reached for it.

Whatever''s making you anxious this week, you''re not the one doing the holding on. He''s already holding you.', 'Which of these four promises — with you, your God, strengthened, upheld — do you need to hear most today?', 'God, when fear tightens my grip, remind me Your hand is already around mine. Strengthen and uphold me today, not because I''ve earned it, but because You said You would. Amen.'),
    ('Romans 8:28', 'All Things Working Together', 'Flip a piece of embroidery over mid-project and all you''ll see is a tangle of knots, loose threads, and colors that seem to go nowhere — it only makes sense from the side the weaver can see. Paul wrote this promise to a church that had every reason to feel like they were looking at the tangled underside of their own lives: persecution, uncertainty, suffering he''d already spent a whole chapter describing.

His claim isn''t that every individual thread will feel good in the moment — it''s that God is actively weaving all of it, including the hard and confusing parts, toward good for those who love Him. That''s a statement about the Weaver''s character, not a promise that pain won''t be real.

Whatever doesn''t make sense in your life this week, you''re not looking at the finished side yet.', 'What''s one "tangled thread" in your life right now that you''re being invited to trust God with, even without seeing the full picture?', 'Father, I don''t always see how the pieces fit together, but I trust You''re weaving them toward good. Give me patience to trust the Weaver even when I can only see the knots. Amen.'),
    ('Proverbs 3:5-6', 'Trust Over Understanding', 'It''s a small, familiar temptation — the GPS says one route, but a side road looks shorter, so you trust your own read of the map instead. Most of the time it costs you a few extra minutes; sometimes it costs a lot more. Solomon''s proverb addresses a much bigger version of that same instinct: leaning on our own understanding instead of trusting the One who actually sees the whole road.

Trusting God "with all your heart" doesn''t mean turning off your mind — it means holding your own understanding loosely enough to let Him redirect it. The promise attached isn''t that the path will always make sense to you; it''s that He will make it straight.

Whatever decision is in front of you this week, bring it to Him before you''re fully confident in your own read of the map.', 'What decision this week are you tempted to navigate purely on your own understanding, without acknowledging God in it?', 'Lord, my understanding is limited but Yours isn''t. I hand You this decision I''ve been carrying alone, and I ask You to make my path straight even when I can''t see the way. Amen.'),
    ('Jeremiah 29:11', 'Plans to Give You Hope', 'This verse shows up on graduation cards and framed office walls, usually stripped of the situation it was actually written into: a letter to people who had just lost their homeland, their temple, and their freedom, told they''d be in exile for seventy years. It wasn''t a promise of an easy season — it was a promise that God''s intentions toward them, even inside that hard season, were for their good.

That distinction matters. If you''re in a season of waiting — for healing, for an answer, for a door to open — this isn''t a guarantee the wait ends this week. It''s a guarantee about the heart of the One who''s holding you through it.

Whatever you''re waiting on right now, God''s plans for you haven''t paused.', 'What are you currently waiting on that''s tempting you to believe God''s plans for you have stalled?', 'God, waiting is hard, and I don''t always trust it while I''m in it. Remind me that Your plans for me are for good even in this in-between season, and give me patience to keep trusting You. Amen.'),
    ('Matthew 11:28-30', 'Rest for the Weary', 'A yoke was built for two animals, not one — and often a farmer would pair a young, untrained ox with an older, stronger one, so the stronger animal absorbed most of the strain while the younger one learned the pace. That''s the image Jesus reaches for when He invites the weary to come to Him: not the removal of all work, but a yoke shared with Someone infinitely stronger.

He doesn''t say "stop laboring" — burdened people don''t usually get to just stop. He says take my yoke, learn from me, and you will find rest for your souls. The rest He offers isn''t the absence of a task; it''s the presence of a partner who''s already carrying the heavier end.

Whatever is exhausting you this week, bring it under His yoke instead of trying to carry it solo.', 'What''s the heavy thing you''ve been carrying alone that Jesus is inviting you to bring under His yoke this week?', 'Jesus, I''m tired, and I''ve been trying to carry this by myself. Thank You for offering to share the weight — teach me to walk at Your pace instead of pushing through on my own strength. Amen.'),
    ('2 Corinthians 5:17', 'A New Creation', 'Some labels are hard to shake — the mistake everyone remembers, the habit you can''t seem to outrun, the reputation a season of your life earned you that you never quite escaped. Paul writes to a church full of people with complicated pasts and tells them plainly: in Christ, the old has genuinely passed away, and something new has already come.

This isn''t a slow renovation project where the old structure is still visible underneath; Paul''s language is demolition and fresh creation. Whatever labeled you before doesn''t get to write the next chapter. You''re not the same person who did that thing, said that thing, or lived through that season the same way.

Walk into this week as who you actually are now — not who you used to be.', 'What old label are you still letting define you, even though it no longer describes who you are in Christ?', 'Lord, thank You for making me new, not just forgiving the old. Help me actually believe that today, and live like the person You''ve already made me, not the person I used to be. Amen.'),
    ('Psalm 46:1', 'A Very Present Help', 'There''s a particular relief in a call being answered on the first ring at 2 a.m. — proof that someone was actually reachable in the exact moment you needed them, not just willing in theory. The psalmist describes God in almost identical terms: not a refuge you have to search for, but "a very present help in trouble," already available in the moment trouble hits.

This psalm was likely written during real national upheaval — mountains figuratively "falling into the heart of the sea," as the following verses describe. Yet the opening line isn''t panic; it''s confidence, because the psalmist knew exactly who was already near.

Whatever trouble shows up this week, you don''t have to wait for God to become available. He already is.', 'What trouble are you facing where you''ve been waiting to feel God''s help, instead of trusting He''s already present in it?', 'God, thank You for being near before I even call out. When trouble comes this week, remind me I''m not waiting for You to show up — You''re already here. Amen.'),
    ('Philippians 4:13', 'Strength Through Christ', 'This verse shows up on gym walls and pre-game pep talks so often that it''s easy to forget where Paul actually wrote it: not before a victory, but from a prison cell, in a passage about learning contentment in both plenty and hunger, in abundance and need (vv. 11-12). The strength he''s talking about isn''t for winning — it''s for enduring whatever circumstance he''s actually in.

That reframes the promise. It''s not a guarantee you''ll accomplish everything you set out to do; it''s an assurance that Christ supplies exactly the strength needed for whatever this week actually holds — plenty or need, comfort or hardship.

Whatever circumstance you''re facing, the strength promised here is sized for it, not for your ambitions.', 'What circumstance this week — not a goal, but an actual circumstance — do you need Christ''s strength to endure well?', 'Christ, I don''t need strength to win everything — I need strength to be content and faithful in whatever this week brings. Thank You for supplying exactly what today requires. Amen.'),
    ('Isaiah 40:31', 'Renewed Strength', 'A phone charged fully overnight runs all day without a second thought; one given five rushed minutes on the way out the door dies by noon. Isaiah''s audience, exhausted and in exile, needed to hear that the same principle applies to their own strength — it isn''t manufactured by pushing harder, it''s renewed by waiting on the One who never grows weary Himself (v. 28).

The images that follow — soaring like eagles, running without weariness, walking without fainting — build in a surprising order: the extraordinary moments (soaring) come easily, but it''s the ordinary, sustained walking that actually requires the deepest renewal.

If you feel worn down from the daily walk of serving and showing up, this is an invitation to plug back into the source before pushing further on empty.', 'Where in your week do you need Isaiah''s kind of walking-strength — not a burst of energy, but sustained renewal?', 'LORD, I''m tired in the ordinary parts of this week, not just the hard ones. Renew my strength as I wait on You, so I can walk faithfully without fainting. Amen.'),
    ('1 Peter 5:7', 'Casting Your Cares', 'It''s easy to forget you''re still carrying something — a backpack slung over one shoulder for hours after you actually needed it, your muscles aching before you even notice why. Peter''s readers were carrying real weight: scattered, persecuted, uncertain of their future. His instruction is strikingly physical — cast, not carefully set down, but actively throw the weight off onto someone else.

The reason he gives isn''t "because worry is unproductive," though it is. It''s because He cares for you — a statement about God''s heart, not just a strategy for your stress levels. You''re not handing your anxiety to an indifferent processor; you''re handing it to Someone who wants to actually carry it.

What have you been carrying out of habit this week that you could finally set down?', 'What worry have you been carrying so long you''ve forgotten how heavy it''s gotten?', 'Father, I''ve been carrying this longer than I needed to. I cast it on You now — not because I''ve stopped caring, but because I finally believe You care more. Amen.'),
    ('Romans 12:2', 'A Renewed Mind', 'Water takes the shape of whatever it''s poured into without any resistance at all — and Paul''s warning about being "conformed to this world" describes exactly that kind of passive shaping, absorbing the culture around you simply because you never pushed back against it. Transformation, by contrast, requires something active: a mind being renewed, not just a behavior being corrected.

That order matters. Paul doesn''t say change your actions and your thinking will follow; he says the renewing of your mind is what produces the ability to discern God''s good, pleasing, and perfect will in the first place. Behavior modification without a changed mind rarely lasts.

As you move through this week, pay attention to what''s actually shaping your thinking — and let Scripture be part of what''s doing the renewing, not just the correcting after the fact.', 'What''s currently pouring into your mind and quietly shaping you, whether or not you''ve noticed it?', 'Lord, I don''t want to just be shaped by whatever''s around me. Renew my mind this week so my choices flow from a heart that''s actually being changed, not just corrected. Amen.'),
    ('Galatians 5:22-23', 'The Fruit of the Spirit', 'You could tape apples onto a bare branch and, from a distance, it might look like an apple tree — but no amount of tape produces actual fruit; only a healthy, rooted tree does that naturally, in its season. Paul''s list here isn''t a checklist of behaviors to strap onto yourself through willpower; it''s fruit, which by definition grows out of a healthy connection to the vine, not effort applied directly to the branch.

That''s why he calls it "fruit of the Spirit" rather than "works of the Spirit" or "rules to follow." Love, joy, peace, patience — these grow as a byproduct of staying rooted in Him, not as things you can manufacture through sheer determination alone.

If patience or gentleness feels thin this week, the fix isn''t trying harder to fake it — it''s staying closer to the root.', 'Which fruit of the Spirit feels thinnest in your life right now, and what would it look like to tend the root instead of the branch?', 'Spirit of God, I can''t manufacture this fruit on my own strength. Keep me rooted in You this week, and let love, patience, and gentleness grow naturally out of that closeness. Amen.'),
    ('Psalm 121:1-2', 'Where Help Comes From', 'There''s a particular kind of midnight moment — scrolling through a contacts list, realizing none of the names on it can actually fix what''s wrong. The psalmist opens with a similarly honest scan: he lifts his eyes to the hills, likely where pagan shrines once stood, and asks out loud where real help is going to come from.

He doesn''t skip past the question to arrive at a tidy answer — he actually voices the uncertainty first. Only then does he land on the source: "my help comes from the LORD, who made heaven and earth," a deliberate contrast between hills that can''t help and the God who made every hill there is.

When you feel stuck this week, it''s worth asking the question out loud too, instead of quietly hoping something else will solve it.', 'Where have you been quietly looking for help this week that isn''t actually able to give it?', 'LORD, You made heaven and earth, and You''re the help I actually need. Turn my eyes away from things that can''t help me, and toward You who made them all. Amen.'),
    ('Hebrews 11:1', 'The Substance of Faith', 'There''s nothing to see when you first water a freshly planted seed — just bare, unremarkable dirt, with no evidence yet that anything is actually happening underneath. Faith, as Hebrews defines it, works the same way: assurance of things hoped for, proof of things not yet seen. It isn''t wishful thinking; it''s confidence that what''s been promised is genuinely underway, even before it''s visible.

The chapter goes on to list people who acted on exactly that kind of unseen confidence — Noah building a boat before rain existed, Abraham leaving home for a land he hadn''t yet received. None of them saw the fulfillment before they acted in faith.

What has God promised that you haven''t seen fulfilled yet? Let this shape how you pray about it this week, even without visible proof.', 'What promise of God are you still watering in faith, even though you can''t see it growing yet?', 'God, help me trust what You''ve promised even before I see it fulfilled. Give me the kind of faith that keeps watering the ground, confident that You''re working beneath the surface. Amen.'),
    ('James 1:2-4', 'Joy in Testing', 'No muscle grows stronger from comfort alone — it grows through resistance, through the actual strain of a weight that''s harder than yesterday''s. James makes a similarly counterintuitive claim about trials: count it all joy, not because the trial itself feels good, but because of what it''s building in you.

His logic moves in a specific order — testing produces endurance, and endurance, if you let it finish its work, produces a kind of completeness that shortcuts never build. That''s a hard word for anyone in the middle of an actual trial; joy here isn''t a feeling to fake, it''s a perspective on what the strain is producing.

If this week is testing your patience or your faith, ask what endurance it might be building in you, rather than only wishing it were over.', 'What trial are you currently in the middle of, and what might it be building in you if you let it finish its work?', 'Lord, this trial is hard, and I don''t always feel joy in it. Help me trust that You''re building endurance in me through it, and give me patience to let it do its work. Amen.'),
    ('Deuteronomy 31:6', 'He Will Not Forsake You', 'A new employee''s first shift is easier the moment a seasoned coworker says, "I''ll be right beside you the whole time" — the task doesn''t get smaller, but the fear does. Moses said something like that to the entire nation of Israel, about to cross into a land full of fortified cities and people they''d feared for forty years.

His command to be strong and courageous isn''t rooted in their own ability to win the coming battles — it''s rooted entirely in a promise of presence: "the LORD your God himself is who goes with you. He will not fail you nor forsake you." Courage, again and again in Scripture, is presence-based, not performance-based.

Whatever intimidating thing is ahead of you this week, you''re being sent into it with Someone walking beside you the whole way.', 'What''s the "fortified city" in your week that feels less intimidating once you remember God is going with you?', 'Lord, thank You for going with me instead of just sending me. Help me face what''s ahead this week with courage rooted in Your presence, not in my own confidence. Amen.'),
    ('Matthew 6:33', 'Seek First', 'It''s remarkably easy to rearrange an entire day around something small — a minor errand, an inbox, a scroll through the phone — while the one thing that actually matters keeps getting quietly pushed to "later." Jesus says this right after telling His listeners not to worry about food or clothing, the most basic, legitimate needs a person has.

His instruction isn''t to ignore those needs — He assumes His Father already knows about them (v. 32). It''s about ordering: seek first His kingdom and His righteousness, and let everything else take its proper, secondary place. Priorities aren''t about having no needs; they''re about which need gets addressed first.

What would it look like this week to seek Him first thing, before the day''s smaller urgencies take over?', 'What''s been quietly claiming the "first" place in your priorities this week that doesn''t belong there?', 'Father, You already know what I need. Help me seek You first this week, before the smaller urgencies crowd You out, and trust You with everything that follows. Amen.'),
    ('1 Corinthians 13:4-7', 'What Love Looks Like', 'Read this passage the way you''d read a job description, and honestly ask whether you''d qualify: patient, kind, not envious, not boastful, not easily provoked, keeping no record of wrongs. Most of us would have to admit we''re a work in progress on at least half the list — Paul wasn''t writing an inspirational quote, he was writing a mirror.

He placed this chapter deliberately in the middle of a letter to a church full of division and spiritual pride, as if to say: whatever gifts you''re proud of, none of it means anything without this. Love here isn''t a feeling; it''s a specific, describable way of treating people, verse by verse.

Pick one line from this list and let it shape one actual interaction you''ll have this week.', 'Which specific line in this passage exposes the interaction you handled worst this past week?', 'Lord, this list convicts me more than it comforts me. Grow this kind of love in me — not as a feeling, but as how I actually treat the people in front of me this week. Amen.'),
    ('Psalm 34:18', 'Near to the Brokenhearted', 'Some of the most meaningful comfort anyone has ever offered isn''t advice — it''s simply presence, a friend who sits quietly beside someone grieving without trying to fix anything at all. David, who wrote this psalm during one of the lowest, most humiliating moments of his life (see the psalm''s heading), knew what it was to be genuinely broken.

His claim isn''t that God is near to the spiritually impressive or the composed — it''s specifically the brokenhearted and crushed in spirit. That nearness isn''t something you earn by managing your grief well; it''s promised precisely in the moments you can''t.

If your heart is heavy this week, that nearness is already true of you, not something you have to perform your way into.', 'Where do you need to simply believe God is near, rather than trying to appear composed enough for Him to come close?', 'LORD, my heart is heavy, and I don''t need to hide that from You. Thank You for being near to the brokenhearted — be near to me now. Amen.'),
    ('Lamentations 3:22-23', 'New Every Morning', 'There''s a particular dread the night before a hard day resumes — as if tomorrow will simply pick up exactly where the awful today left off. Jeremiah wrote this line in the middle of the book of Lamentations, a raw, unflinching account of grief over Jerusalem''s destruction — this isn''t hope in spite of honesty about pain, it''s hope stated right in the middle of it.

His claim is startlingly specific: God''s compassions don''t run out overnight and arrive depleted the next day — they are new every morning. Mercy isn''t a finite resource being rationed out; it''s freshly given, every single day, regardless of how much was needed yesterday.

Whatever didn''t go right last week, God''s mercy toward you this morning isn''t running on what''s left over.', 'What from last week are you tempted to believe God''s mercy toward you is still recovering from?', 'Lord, thank You that Your mercies are new this morning, not carried over depleted from yesterday. Meet me fresh today, regardless of how hard last week was. Amen.')
) as v(scripture_reference, title, reflection, reflection_question, prayer)
where d.scripture_reference = v.scripture_reference;

-- Same rewrite for the self-service seed function future orgs get
-- (src/app/onboarding/actions.ts calls this right after org creation).
create or replace function public.seed_default_devotionals(p_org_id uuid)
returns void
language plpgsql security definer
set search_path = public
as $seed$
begin
  if not exists (
    select 1 from profiles
    where id = auth.uid() and org_id = p_org_id and role = 'admin'
  ) then
    raise exception 'Not authorized to seed devotionals for this organization';
  end if;

  if exists (select 1 from devotionals where org_id = p_org_id) then
    return;
  end if;

  insert into devotionals (org_id, title, scripture_reference, scripture_text, reflection, reflection_question, prayer, sort_order)
  values
    (p_org_id, 'God''s Great Love', 'John 3:16', 'For God so loved the world, that he gave his one and only Son, that whoever believes in him should not perish, but have eternal life.', 'Most of us know at least one parent who''d give up their last dollar, their last hour of sleep, or their own comfort for their child without a second thought — and we call that ordinary love. John describes something far larger: the Creator of the universe giving up His only Son, not for people who''d earned it, but for a world that had turned away from Him.

That''s the whole gospel compressed into one verse — God moved first, before we asked, before we deserved it, before we even knew we needed it. Belief isn''t the price we pay for that love; it''s simply how we receive what''s already been given.

Whatever this week holds, you don''t have to perform your way into God''s affection. You can serve, work, and love other people from a place of already being loved, instead of trying to earn a love you already have.', 'Where this week have you been trying to earn love that God has already freely given you?', 'Father, thank You for loving me before I ever turned toward You. Help me receive Your love today instead of working for it, and let it overflow into how I treat the people around me. Amen.', 1),
    (p_org_id, 'Peace That Guards Your Heart', 'Philippians 4:6-7', 'In nothing be anxious, but in everything, by prayer and petition with thanksgiving, let your requests be made known to God. And the peace of God, which surpasses all understanding, will guard your hearts and your thoughts in Christ Jesus.', 'Anxiety has a way of running the same loop over and over without ever actually solving anything — you can replay a hard conversation fifty times and still feel just as unsettled by evening. Paul, writing this letter from prison, knew that loop well, yet he tells a whole church not to be anxious about anything.

His instruction isn''t to suppress the worry but to redirect it — to turn it into a specific prayer, made with thanksgiving even before the outcome is known. What follows isn''t a guaranteed fix to the circumstance, but something better: a peace that doesn''t depend on the circumstance being fixed at all.

Name the thing that''s looping in your mind this week. Bring it to God in a specific prayer today, and ask Him to stand guard over your heart while you wait.', 'What specific worry could you turn into a specific prayer today, instead of just carrying it silently?', 'Lord, I bring You what''s been circling in my mind. Thank You in advance for how You''ll care for it, and guard my heart with a peace I can''t manufacture on my own. Amen.', 2),
    (p_org_id, 'The Shepherd Who Restores', 'Psalm 23:1-3', 'The LORD is my shepherd: I shall lack nothing. He makes me lie down in green pastures. He leads me beside still waters. He restores my soul. He guides me in the paths of righteousness for his name''s sake.', 'It''s easy to mistake constant activity for faithfulness — to keep saying yes to one more task, one more shift, one more need, until you''re running on fumes and calling it devotion. David, a shepherd himself before he was a king, knew that even sheep have to be made to lie down; left to themselves, they''ll graze anxiously until they collapse.

That''s exactly the image he uses for God''s care: a shepherd who doesn''t just point out the pasture but leads His people into rest, and doesn''t just feed the body but restores the soul. Rest here isn''t a reward for finishing the work — it''s part of how the Shepherd cares for those who serve.

If you''re running low this week, this isn''t permission to quit serving — it''s an invitation to let God restore you before you serve again.', 'What would it look like this week to let God restore you before your next act of service, instead of after you''ve run out?', 'Shepherd God, restore what serving has emptied out of me. Lead me somewhere quiet before You send me out again, and remind me that resting in You is not wasted time. Amen.', 3),
    (p_org_id, 'Strong and Courageous', 'Joshua 1:9', 'Haven''t I commanded you? Be strong and courageous. Don''t be afraid. Don''t be dismayed, for the LORD your God is with you wherever you go.', 'Nobody feels fully ready for the role that finally arrives — the promotion, the new city, the responsibility that''s suddenly yours. Joshua had spent decades as Moses'' assistant, and now he was being handed an entire nation and a land full of giants, with the man who''d led everything before him gone.

God''s command to Joshua isn''t a pep talk about self-confidence — it''s grounded entirely in a promise of presence: "the LORD your God is with you wherever you go." Courage, in Scripture, is rarely the absence of fear; it''s obedience that moves forward anyway because of who''s walking alongside you.

Whatever new responsibility or unfamiliar ground you''re stepping into this week, you''re not being sent out to prove yourself alone.', 'What''s the "giant" in front of you this week that feels too big to face on your own strength?', 'Lord, I don''t feel ready for what''s ahead, but You never asked me to be strong by myself. Go with me into this week, and let Your presence be enough for my courage. Amen.', 4),
    (p_org_id, 'Held By His Hand', 'Isaiah 41:10', 'Don''t you be afraid, for I am with you. Don''t be dismayed, for I am your God. I will strengthen you. Yes, I will help you. Yes, I will uphold you with the right hand of my righteousness.', 'There''s a particular kind of grip a small child uses crossing a crowded parking lot — not casual, but urgent, both hands, holding on as if letting go for even a second would be dangerous. Isaiah''s audience needed that same kind of grip; they were a people facing exile, invasion, and real reason to be afraid.

God doesn''t respond with a vague reassurance — He stacks four specific promises in one breath: I am with you, I am your God, I will strengthen you, I will uphold you. This isn''t distant comfort; it''s a hand that''s already closed around theirs before they even reached for it.

Whatever''s making you anxious this week, you''re not the one doing the holding on. He''s already holding you.', 'Which of these four promises — with you, your God, strengthened, upheld — do you need to hear most today?', 'God, when fear tightens my grip, remind me Your hand is already around mine. Strengthen and uphold me today, not because I''ve earned it, but because You said You would. Amen.', 5),
    (p_org_id, 'All Things Working Together', 'Romans 8:28', 'We know that all things work together for good for those who love God, to those who are called according to his purpose.', 'Flip a piece of embroidery over mid-project and all you''ll see is a tangle of knots, loose threads, and colors that seem to go nowhere — it only makes sense from the side the weaver can see. Paul wrote this promise to a church that had every reason to feel like they were looking at the tangled underside of their own lives: persecution, uncertainty, suffering he''d already spent a whole chapter describing.

His claim isn''t that every individual thread will feel good in the moment — it''s that God is actively weaving all of it, including the hard and confusing parts, toward good for those who love Him. That''s a statement about the Weaver''s character, not a promise that pain won''t be real.

Whatever doesn''t make sense in your life this week, you''re not looking at the finished side yet.', 'What''s one "tangled thread" in your life right now that you''re being invited to trust God with, even without seeing the full picture?', 'Father, I don''t always see how the pieces fit together, but I trust You''re weaving them toward good. Give me patience to trust the Weaver even when I can only see the knots. Amen.', 6),
    (p_org_id, 'Trust Over Understanding', 'Proverbs 3:5-6', 'Trust in the LORD with all your heart, and don''t lean on your own understanding. In all your ways acknowledge him, and he will make your paths straight.', 'It''s a small, familiar temptation — the GPS says one route, but a side road looks shorter, so you trust your own read of the map instead. Most of the time it costs you a few extra minutes; sometimes it costs a lot more. Solomon''s proverb addresses a much bigger version of that same instinct: leaning on our own understanding instead of trusting the One who actually sees the whole road.

Trusting God "with all your heart" doesn''t mean turning off your mind — it means holding your own understanding loosely enough to let Him redirect it. The promise attached isn''t that the path will always make sense to you; it''s that He will make it straight.

Whatever decision is in front of you this week, bring it to Him before you''re fully confident in your own read of the map.', 'What decision this week are you tempted to navigate purely on your own understanding, without acknowledging God in it?', 'Lord, my understanding is limited but Yours isn''t. I hand You this decision I''ve been carrying alone, and I ask You to make my path straight even when I can''t see the way. Amen.', 7),
    (p_org_id, 'Plans to Give You Hope', 'Jeremiah 29:11', 'For I know the thoughts that I think toward you, says the LORD, thoughts of peace, and not of evil, to give you hope and a future.', 'This verse shows up on graduation cards and framed office walls, usually stripped of the situation it was actually written into: a letter to people who had just lost their homeland, their temple, and their freedom, told they''d be in exile for seventy years. It wasn''t a promise of an easy season — it was a promise that God''s intentions toward them, even inside that hard season, were for their good.

That distinction matters. If you''re in a season of waiting — for healing, for an answer, for a door to open — this isn''t a guarantee the wait ends this week. It''s a guarantee about the heart of the One who''s holding you through it.

Whatever you''re waiting on right now, God''s plans for you haven''t paused.', 'What are you currently waiting on that''s tempting you to believe God''s plans for you have stalled?', 'God, waiting is hard, and I don''t always trust it while I''m in it. Remind me that Your plans for me are for good even in this in-between season, and give me patience to keep trusting You. Amen.', 8),
    (p_org_id, 'Rest for the Weary', 'Matthew 11:28-30', 'Come to me, all you who labor and are heavily burdened, and I will give you rest. Take my yoke upon you, and learn from me, for I am gentle and humble in heart; and you will find rest for your souls. For my yoke is easy, and my burden is light.', 'A yoke was built for two animals, not one — and often a farmer would pair a young, untrained ox with an older, stronger one, so the stronger animal absorbed most of the strain while the younger one learned the pace. That''s the image Jesus reaches for when He invites the weary to come to Him: not the removal of all work, but a yoke shared with Someone infinitely stronger.

He doesn''t say "stop laboring" — burdened people don''t usually get to just stop. He says take my yoke, learn from me, and you will find rest for your souls. The rest He offers isn''t the absence of a task; it''s the presence of a partner who''s already carrying the heavier end.

Whatever is exhausting you this week, bring it under His yoke instead of trying to carry it solo.', 'What''s the heavy thing you''ve been carrying alone that Jesus is inviting you to bring under His yoke this week?', 'Jesus, I''m tired, and I''ve been trying to carry this by myself. Thank You for offering to share the weight — teach me to walk at Your pace instead of pushing through on my own strength. Amen.', 9),
    (p_org_id, 'A New Creation', '2 Corinthians 5:17', 'Therefore if anyone is in Christ, he is a new creation. The old things have passed away. Behold, all things have become new.', 'Some labels are hard to shake — the mistake everyone remembers, the habit you can''t seem to outrun, the reputation a season of your life earned you that you never quite escaped. Paul writes to a church full of people with complicated pasts and tells them plainly: in Christ, the old has genuinely passed away, and something new has already come.

This isn''t a slow renovation project where the old structure is still visible underneath; Paul''s language is demolition and fresh creation. Whatever labeled you before doesn''t get to write the next chapter. You''re not the same person who did that thing, said that thing, or lived through that season the same way.

Walk into this week as who you actually are now — not who you used to be.', 'What old label are you still letting define you, even though it no longer describes who you are in Christ?', 'Lord, thank You for making me new, not just forgiving the old. Help me actually believe that today, and live like the person You''ve already made me, not the person I used to be. Amen.', 10),
    (p_org_id, 'A Very Present Help', 'Psalm 46:1', 'God is our refuge and strength, a very present help in trouble.', 'There''s a particular relief in a call being answered on the first ring at 2 a.m. — proof that someone was actually reachable in the exact moment you needed them, not just willing in theory. The psalmist describes God in almost identical terms: not a refuge you have to search for, but "a very present help in trouble," already available in the moment trouble hits.

This psalm was likely written during real national upheaval — mountains figuratively "falling into the heart of the sea," as the following verses describe. Yet the opening line isn''t panic; it''s confidence, because the psalmist knew exactly who was already near.

Whatever trouble shows up this week, you don''t have to wait for God to become available. He already is.', 'What trouble are you facing where you''ve been waiting to feel God''s help, instead of trusting He''s already present in it?', 'God, thank You for being near before I even call out. When trouble comes this week, remind me I''m not waiting for You to show up — You''re already here. Amen.', 11),
    (p_org_id, 'Strength Through Christ', 'Philippians 4:13', 'I can do all things through Christ, who strengthens me.', 'This verse shows up on gym walls and pre-game pep talks so often that it''s easy to forget where Paul actually wrote it: not before a victory, but from a prison cell, in a passage about learning contentment in both plenty and hunger, in abundance and need (vv. 11-12). The strength he''s talking about isn''t for winning — it''s for enduring whatever circumstance he''s actually in.

That reframes the promise. It''s not a guarantee you''ll accomplish everything you set out to do; it''s an assurance that Christ supplies exactly the strength needed for whatever this week actually holds — plenty or need, comfort or hardship.

Whatever circumstance you''re facing, the strength promised here is sized for it, not for your ambitions.', 'What circumstance this week — not a goal, but an actual circumstance — do you need Christ''s strength to endure well?', 'Christ, I don''t need strength to win everything — I need strength to be content and faithful in whatever this week brings. Thank You for supplying exactly what today requires. Amen.', 12),
    (p_org_id, 'Renewed Strength', 'Isaiah 40:31', 'But those who wait for the LORD will renew their strength. They will mount up with wings like eagles. They will run, and not be weary. They will walk, and not faint.', 'A phone charged fully overnight runs all day without a second thought; one given five rushed minutes on the way out the door dies by noon. Isaiah''s audience, exhausted and in exile, needed to hear that the same principle applies to their own strength — it isn''t manufactured by pushing harder, it''s renewed by waiting on the One who never grows weary Himself (v. 28).

The images that follow — soaring like eagles, running without weariness, walking without fainting — build in a surprising order: the extraordinary moments (soaring) come easily, but it''s the ordinary, sustained walking that actually requires the deepest renewal.

If you feel worn down from the daily walk of serving and showing up, this is an invitation to plug back into the source before pushing further on empty.', 'Where in your week do you need Isaiah''s kind of walking-strength — not a burst of energy, but sustained renewal?', 'LORD, I''m tired in the ordinary parts of this week, not just the hard ones. Renew my strength as I wait on You, so I can walk faithfully without fainting. Amen.', 13),
    (p_org_id, 'Casting Your Cares', '1 Peter 5:7', 'casting all your worries on him, because he cares for you.', 'It''s easy to forget you''re still carrying something — a backpack slung over one shoulder for hours after you actually needed it, your muscles aching before you even notice why. Peter''s readers were carrying real weight: scattered, persecuted, uncertain of their future. His instruction is strikingly physical — cast, not carefully set down, but actively throw the weight off onto someone else.

The reason he gives isn''t "because worry is unproductive," though it is. It''s because He cares for you — a statement about God''s heart, not just a strategy for your stress levels. You''re not handing your anxiety to an indifferent processor; you''re handing it to Someone who wants to actually carry it.

What have you been carrying out of habit this week that you could finally set down?', 'What worry have you been carrying so long you''ve forgotten how heavy it''s gotten?', 'Father, I''ve been carrying this longer than I needed to. I cast it on You now — not because I''ve stopped caring, but because I finally believe You care more. Amen.', 14),
    (p_org_id, 'A Renewed Mind', 'Romans 12:2', 'Don''t be conformed to this world, but be transformed by the renewing of your mind, so that you may prove what is the good, well-pleasing, and perfect will of God.', 'Water takes the shape of whatever it''s poured into without any resistance at all — and Paul''s warning about being "conformed to this world" describes exactly that kind of passive shaping, absorbing the culture around you simply because you never pushed back against it. Transformation, by contrast, requires something active: a mind being renewed, not just a behavior being corrected.

That order matters. Paul doesn''t say change your actions and your thinking will follow; he says the renewing of your mind is what produces the ability to discern God''s good, pleasing, and perfect will in the first place. Behavior modification without a changed mind rarely lasts.

As you move through this week, pay attention to what''s actually shaping your thinking — and let Scripture be part of what''s doing the renewing, not just the correcting after the fact.', 'What''s currently pouring into your mind and quietly shaping you, whether or not you''ve noticed it?', 'Lord, I don''t want to just be shaped by whatever''s around me. Renew my mind this week so my choices flow from a heart that''s actually being changed, not just corrected. Amen.', 15),
    (p_org_id, 'The Fruit of the Spirit', 'Galatians 5:22-23', 'But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faith, gentleness, and self-control. Against such things there is no law.', 'You could tape apples onto a bare branch and, from a distance, it might look like an apple tree — but no amount of tape produces actual fruit; only a healthy, rooted tree does that naturally, in its season. Paul''s list here isn''t a checklist of behaviors to strap onto yourself through willpower; it''s fruit, which by definition grows out of a healthy connection to the vine, not effort applied directly to the branch.

That''s why he calls it "fruit of the Spirit" rather than "works of the Spirit" or "rules to follow." Love, joy, peace, patience — these grow as a byproduct of staying rooted in Him, not as things you can manufacture through sheer determination alone.

If patience or gentleness feels thin this week, the fix isn''t trying harder to fake it — it''s staying closer to the root.', 'Which fruit of the Spirit feels thinnest in your life right now, and what would it look like to tend the root instead of the branch?', 'Spirit of God, I can''t manufacture this fruit on my own strength. Keep me rooted in You this week, and let love, patience, and gentleness grow naturally out of that closeness. Amen.', 16),
    (p_org_id, 'Where Help Comes From', 'Psalm 121:1-2', 'I will lift up my eyes to the hills. Where does my help come from? My help comes from the LORD, who made heaven and earth.', 'There''s a particular kind of midnight moment — scrolling through a contacts list, realizing none of the names on it can actually fix what''s wrong. The psalmist opens with a similarly honest scan: he lifts his eyes to the hills, likely where pagan shrines once stood, and asks out loud where real help is going to come from.

He doesn''t skip past the question to arrive at a tidy answer — he actually voices the uncertainty first. Only then does he land on the source: "my help comes from the LORD, who made heaven and earth," a deliberate contrast between hills that can''t help and the God who made every hill there is.

When you feel stuck this week, it''s worth asking the question out loud too, instead of quietly hoping something else will solve it.', 'Where have you been quietly looking for help this week that isn''t actually able to give it?', 'LORD, You made heaven and earth, and You''re the help I actually need. Turn my eyes away from things that can''t help me, and toward You who made them all. Amen.', 17),
    (p_org_id, 'The Substance of Faith', 'Hebrews 11:1', 'Now faith is assurance of things hoped for, proof of things not seen.', 'There''s nothing to see when you first water a freshly planted seed — just bare, unremarkable dirt, with no evidence yet that anything is actually happening underneath. Faith, as Hebrews defines it, works the same way: assurance of things hoped for, proof of things not yet seen. It isn''t wishful thinking; it''s confidence that what''s been promised is genuinely underway, even before it''s visible.

The chapter goes on to list people who acted on exactly that kind of unseen confidence — Noah building a boat before rain existed, Abraham leaving home for a land he hadn''t yet received. None of them saw the fulfillment before they acted in faith.

What has God promised that you haven''t seen fulfilled yet? Let this shape how you pray about it this week, even without visible proof.', 'What promise of God are you still watering in faith, even though you can''t see it growing yet?', 'God, help me trust what You''ve promised even before I see it fulfilled. Give me the kind of faith that keeps watering the ground, confident that You''re working beneath the surface. Amen.', 18),
    (p_org_id, 'Joy in Testing', 'James 1:2-4', 'Count it all joy, my brothers, when you fall into various temptations, knowing that the testing of your faith produces endurance. Let endurance have its perfect work, that you may be perfect and complete, lacking in nothing.', 'No muscle grows stronger from comfort alone — it grows through resistance, through the actual strain of a weight that''s harder than yesterday''s. James makes a similarly counterintuitive claim about trials: count it all joy, not because the trial itself feels good, but because of what it''s building in you.

His logic moves in a specific order — testing produces endurance, and endurance, if you let it finish its work, produces a kind of completeness that shortcuts never build. That''s a hard word for anyone in the middle of an actual trial; joy here isn''t a feeling to fake, it''s a perspective on what the strain is producing.

If this week is testing your patience or your faith, ask what endurance it might be building in you, rather than only wishing it were over.', 'What trial are you currently in the middle of, and what might it be building in you if you let it finish its work?', 'Lord, this trial is hard, and I don''t always feel joy in it. Help me trust that You''re building endurance in me through it, and give me patience to let it do its work. Amen.', 19),
    (p_org_id, 'He Will Not Forsake You', 'Deuteronomy 31:6', 'Be strong and courageous. Don''t be afraid or scared of them; for the LORD your God himself is who goes with you. He will not fail you nor forsake you.', 'A new employee''s first shift is easier the moment a seasoned coworker says, "I''ll be right beside you the whole time" — the task doesn''t get smaller, but the fear does. Moses said something like that to the entire nation of Israel, about to cross into a land full of fortified cities and people they''d feared for forty years.

His command to be strong and courageous isn''t rooted in their own ability to win the coming battles — it''s rooted entirely in a promise of presence: "the LORD your God himself is who goes with you. He will not fail you nor forsake you." Courage, again and again in Scripture, is presence-based, not performance-based.

Whatever intimidating thing is ahead of you this week, you''re being sent into it with Someone walking beside you the whole way.', 'What''s the "fortified city" in your week that feels less intimidating once you remember God is going with you?', 'Lord, thank You for going with me instead of just sending me. Help me face what''s ahead this week with courage rooted in Your presence, not in my own confidence. Amen.', 20),
    (p_org_id, 'Seek First', 'Matthew 6:33', 'But seek first God''s Kingdom, and his righteousness; and all these things will be given to you as well.', 'It''s remarkably easy to rearrange an entire day around something small — a minor errand, an inbox, a scroll through the phone — while the one thing that actually matters keeps getting quietly pushed to "later." Jesus says this right after telling His listeners not to worry about food or clothing, the most basic, legitimate needs a person has.

His instruction isn''t to ignore those needs — He assumes His Father already knows about them (v. 32). It''s about ordering: seek first His kingdom and His righteousness, and let everything else take its proper, secondary place. Priorities aren''t about having no needs; they''re about which need gets addressed first.

What would it look like this week to seek Him first thing, before the day''s smaller urgencies take over?', 'What''s been quietly claiming the "first" place in your priorities this week that doesn''t belong there?', 'Father, You already know what I need. Help me seek You first this week, before the smaller urgencies crowd You out, and trust You with everything that follows. Amen.', 21),
    (p_org_id, 'What Love Looks Like', '1 Corinthians 13:4-7', 'Love is patient and is kind; love doesn''t envy. Love doesn''t brag, is not proud, doesn''t behave itself inappropriately, doesn''t seek its own way, is not provoked, takes no account of evil; doesn''t rejoice in unrighteousness, but rejoices with the truth; bears all things, believes all things, hopes all things, endures all things.', 'Read this passage the way you''d read a job description, and honestly ask whether you''d qualify: patient, kind, not envious, not boastful, not easily provoked, keeping no record of wrongs. Most of us would have to admit we''re a work in progress on at least half the list — Paul wasn''t writing an inspirational quote, he was writing a mirror.

He placed this chapter deliberately in the middle of a letter to a church full of division and spiritual pride, as if to say: whatever gifts you''re proud of, none of it means anything without this. Love here isn''t a feeling; it''s a specific, describable way of treating people, verse by verse.

Pick one line from this list and let it shape one actual interaction you''ll have this week.', 'Which specific line in this passage exposes the interaction you handled worst this past week?', 'Lord, this list convicts me more than it comforts me. Grow this kind of love in me — not as a feeling, but as how I actually treat the people in front of me this week. Amen.', 22),
    (p_org_id, 'Near to the Brokenhearted', 'Psalm 34:18', 'The LORD is near to those who have a broken heart, and saves those who have a crushed spirit.', 'Some of the most meaningful comfort anyone has ever offered isn''t advice — it''s simply presence, a friend who sits quietly beside someone grieving without trying to fix anything at all. David, who wrote this psalm during one of the lowest, most humiliating moments of his life (see the psalm''s heading), knew what it was to be genuinely broken.

His claim isn''t that God is near to the spiritually impressive or the composed — it''s specifically the brokenhearted and crushed in spirit. That nearness isn''t something you earn by managing your grief well; it''s promised precisely in the moments you can''t.

If your heart is heavy this week, that nearness is already true of you, not something you have to perform your way into.', 'Where do you need to simply believe God is near, rather than trying to appear composed enough for Him to come close?', 'LORD, my heart is heavy, and I don''t need to hide that from You. Thank You for being near to the brokenhearted — be near to me now. Amen.', 23),
    (p_org_id, 'New Every Morning', 'Lamentations 3:22-23', 'It is because of the LORD''s loving kindnesses that we are not consumed, because his compassion doesn''t fail. They are new every morning. Great is your faithfulness.', 'There''s a particular dread the night before a hard day resumes — as if tomorrow will simply pick up exactly where the awful today left off. Jeremiah wrote this line in the middle of the book of Lamentations, a raw, unflinching account of grief over Jerusalem''s destruction — this isn''t hope in spite of honesty about pain, it''s hope stated right in the middle of it.

His claim is startlingly specific: God''s compassions don''t run out overnight and arrive depleted the next day — they are new every morning. Mercy isn''t a finite resource being rationed out; it''s freshly given, every single day, regardless of how much was needed yesterday.

Whatever didn''t go right last week, God''s mercy toward you this morning isn''t running on what''s left over.', 'What from last week are you tempted to believe God''s mercy toward you is still recovering from?', 'Lord, thank You that Your mercies are new this morning, not carried over depleted from yesterday. Meet me fresh today, regardless of how hard last week was. Amen.', 24);
end;
$seed$;
